version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "jay-platform/edge-service"
    BASE_IMAGES_REPO_NAME: "jay-platform/base-images"

phases:
  pre_build:
    commands:
      - "echo Logging in to ECR..."
      - "ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)"
      - "REPO_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}"
      - "BASE_REPO=${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${BASE_IMAGES_REPO_NAME}"
      - "aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
      - "IMAGE_TAG=git-${CODEBUILD_RESOLVED_SOURCE_VERSION}-${CODEBUILD_BUILD_NUMBER}"
      - "echo Resolved image tag: ${IMAGE_TAG}"
      - "echo Repo URI: ${REPO_URI}"

  build:
    commands:
      - "echo Building image ${REPO_URI}:${IMAGE_TAG}"
      - "docker build --build-arg BUILD_IMAGE=${BASE_REPO}:eclipse-temurin-25-jdk --build-arg RUNTIME_IMAGE=${BASE_REPO}:eclipse-temurin-25-jre -t edge-service:${IMAGE_TAG} ."
      - "docker tag edge-service:${IMAGE_TAG} ${REPO_URI}:${IMAGE_TAG}"

  post_build:
    commands:
      - 'echo Pushing to ECR...'
      - 'docker push ${REPO_URI}:${IMAGE_TAG}'
      - 'echo Generating appspec.yaml...'
      - 'printf "version: 0.0\nResources:\n  - TargetService:\n      Type: AWS::ECS::Service\n      Properties:\n        TaskDefinition: taskdef.json\n        LoadBalancerInfo:\n          ContainerName: app\n          ContainerPort: 8080\n" > appspec.yaml'
      - 'echo Fetching current task definition from ECS service...'
      - 'TASKDEF_ARN=$(aws ecs describe-services --cluster ecs-cluster-prod --services edge-service-prod --query "services[0].taskDefinition" --output text)'
      - 'aws ecs describe-task-definition --task-definition "$TASKDEF_ARN" --query "taskDefinition" --output json > taskdef.json'
      - 'echo Patching taskdef.json image + removing read-only fields...'
      - 'python -c "import json,os; td=json.load(open(\"taskdef.json\")); img=f\"{os.environ[\"REPO_URI\"]}:{os.environ[\"IMAGE_TAG\"]}\"; [c.__setitem__(\"image\",img) for c in td.get(\"containerDefinitions\",[]) if c.get(\"name\")==\"app\"]; [td.pop(k,None) for k in [\"taskDefinitionArn\",\"revision\",\"status\",\"requiresAttributes\",\"compatibilities\",\"registeredAt\",\"registeredBy\",\"deregisteredAt\"]]; json.dump(td,open(\"taskdef.json\",\"w\"),indent=2); print(\"patched image:\",img)"'
      - 'echo Generated files:'
      - 'ls -la appspec.yaml taskdef.json'
      - 'echo appspec.yaml:'
      - 'cat appspec.yaml'

artifacts:
  files:
    - "appspec.yaml"
    - "taskdef.json"
