version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "jay-platform/edge-service"

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPO_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - IMAGE_TAG=git-${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo "Resolved image tag: ${IMAGE_TAG}"
      - echo "Repo URI: ${REPO_URI}"

  build:
    commands:
      - echo "Building image ${REPO_URI}:${IMAGE_TAG}"
      - docker build -t edge-service:${IMAGE_TAG} .
      - docker tag edge-service:${IMAGE_TAG} ${REPO_URI}:${IMAGE_TAG}

  post_build:
    commands:
      - echo "Pushing to ECR..."
      - docker push ${REPO_URI}:${IMAGE_TAG}
      - printf '[{"name":"app","imageUri":"%s"}]' "${REPO_URI}:${IMAGE_TAG}" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
